import './index.scss'

export * from './common/utils/basex'
export * from './common/utils/datetime'
export * from './common/utils/media'
export * from './common/utils/mime'
export * from './common/utils/pagination'
export * from './common/utils/query'
export * from './common/utils/rand'
export * from './common/utils/string'
export * from './common/utils/uri'
export * from './common/utils/html'
export * from './common/utils/email'
export * from './common/utils/uuid'
export * from './common/empty'
export * from './common/error'
export * from './common/link'
export * from './common/loading'
export * from './common/pagination'
export * from './common/component'
export * from './common/jsxFactory'
export * from './common/light/button/filled'
export * from './common/light/button/text'
export * from './common/models/toc'
export * from './common/models/stele'
export * from './common/parser/markdown'
export * from './common/parser/view'

export function sayHelloCommon(word: string) {
    return "Hello from Common!" + word
}
